config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testerpyo:
      branch: main
      repo: https://github.com/PalomoIFCA/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-carmine-stingray.sh
        container: qc.acc_snappy-emerald-oriole
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-teal-ladybird.sh
        container: qc.doc_squirrely-sangria-leopard
      github.com/PalomoIFCA/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-silver-grouse.sh
        container: qc.doc_cheeky-linen-hedgehog
      github.com/PalomoIFCA/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-blue-wolfhound.sh
        container: qc.doc_surly-taupe-mau
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-gold-bloodhound.sh
        container: qc.lic_homely-cinnabar-stingray
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testerpyo pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sepia-quokka.sh
        container: qc.sty_chummy-fuchsia-stoat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-heliotrope-otter.sh
        container: qc.ver_squirrely-cerise-squirt
timeout: 5400
