config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/testerpyo:
      branch: main
      repo: https://github.com/PalomoIFCA/testerpyo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-zucchini-leopard.sh
        container: qc.acc_frumpy-heliotrope-vulture
  QC.Doc:
    repos:
      github.com/PalomoIFCA/testerpyo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lavender-falcon.sh
        container: qc.doc_thirsty-eggplant-cuscus
      github.com/PalomoIFCA/testerpyo git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-panda.sh
        container: qc.doc_shabby-cerulean-wasp
      github.com/PalomoIFCA/testerpyo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olive-squid.sh
        container: qc.doc_scanty-rose-chinook
  QC.Lic:
    repos:
      github.com/PalomoIFCA/testerpyo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-vermilion-robin.sh
        container: qc.lic_scaly-harlequin-cichlid
  QC.Sty:
    repos:
      github.com/PalomoIFCA/testerpyo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-sapphire-frigatebird.sh
        container: qc.sty_snippy-tomato-olm
  QC.Ver:
    repos:
      github.com/PalomoIFCA/testerpyo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lime-spaniel.sh
        container: qc.ver_goopy-beige-eagle
timeout: 5400
