services:
  qc.acc_skanky-chocolate-magpie:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_flabby-salmon-kakapo:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_ready-cerise-bison:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_shaky-champagne-quoll:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_hasty-celadon-penguin:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_nerdy-maroon-dalmatian:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/jsonlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_squirrely-sepia-mammoth:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/pynblint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_woozy-amethyst-ferret:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
